### ISSUE TITLE
Docker or server auto restart

### ISSUE THREAD

**Issue by HellCatVN** [hmes98318/palworld-docker#2]
Server usually disconnected player after 15 min . When I check docker container uptime it also show that uptime is 1 hours or 30 min ago maybe docker or game have issues ?

I am using VPS 8 core 16GB

**Comment by hmes98318** [comment]
Disconnected every 15 minutes? Is the network connection between you and the server stable?  
Can you reconnect directly after being disconnected or do you need to restart the container to connect?  
Try to ping the server continuously while playing, and check if the ping is still maintained when disconnected.

**Comment by HellCatVN** [comment]
Yes connection is stable about 100ms . We can reconnect after 1 or 2 min . Yes server still alive but I don't know why docker or game disconnect us

**Comment by HellCatVN** [comment]
This just happen after playing more than 3 hours

**Comment by hmes98318** [comment]
Try other vps nodes whether they can provide a more stable network connection  
If the same problem occurs again, it should be a problem with the game.  

Currently, I have 2 servers deployed and this problem has not occurred yet.

**Comment by HellCatVN** [comment]
Seem like game memory leak of the game

**Comment by HellCatVN** [comment]
We need to do cron job to restart docker after specific hours and do game backup also

**Comment by hmes98318** [comment]
You can write a simple shell script to automatically restart and backup the save folder.  
Does your vps have more than 16G of ram? If not, it is easier to have a memory leak and crash.

**Comment by HellCatVN** [comment]
Yes we plan to using 32 GB Ram
