### ISSUE TITLE
Suggestion | Support for ARM architecture

### ISSUE THREAD

**Issue by CKwasd** [hmes98318/palworld-docker#3]
Support for ARM architecture
https://dockerworld.cn/?id=316
可以參考一下這個教程 麻煩你了!

**Comment by hmes98318** [comment]
The base image used by the current repository is [cm2network/steamcmd](https://hub.docker.com/r/cm2network/steamcmd/tags), this image only supports the linux/amd64 architecture, so it cannot be built.  
I will try to build an ARM version of the container from scratch  

當前存儲庫所使用的基礎鏡像為 [cm2network/steamcmd](https://hub.docker.com/r/cm2network/steamcmd/tags)，此鏡像僅支援 linux/amd64 架構,所以無法構建  
我會嘗試從頭構建一個 ARM 版本的容器

**Comment by hmes98318** [comment]
我把 linux/arm64 的鏡像推上去 docker hub 就會把 linux/amd64 的鏡像蓋掉，不知道為什麼  
可以先使用 Dockerfile_arm64 檔案進行構建，只能在純 arm64 平台構建，如果用 x86_64 跑 [qemu emulator](https://github.com/tonistiigi/binfmt) 會過不了  

Mac M1 那系列要指定 arm64 平台，不然會預設是會自己轉譯成 x86_64  
(ex: `docker build --platform linux/arm64 -f Dockerfile_arm64 -t palworld-docker .`)  

Raspberry Pi 直接構建沒問題，但遊玩效能低落 : (

**Comment by CKwasd** [comment]
ARM除了M芯片其他都很難跑起來,4+24的vm在五個人遊玩是也只剩下10至15fps
目前在用這個 https://github.com/zion-c/palworld-server-arm64
未來再測試這個https://github.com/yumusb/palworld-server-docker-arm

**Comment by hmes98318** [comment]
那兩個存儲庫的程式碼是一樣的，都是用 [TeriyakiGod/steamcmd-docker-arm64](https://github.com/TeriyakiGod/steamcmd-docker-arm64) 的存儲庫來修改安裝 palworld，我也是用跟他們一樣的方法  

底層用 [FEX emulator](https://github.com/FEX-Emu/FEX) 模擬 x86_64 運行 steamcmd 跟 palworld，我有試過用 [box86](https://github.com/ptitSeb/box86), [box64](https://github.com/ptitSeb/box64) 來運行，但常常會無法運行，只有 FEX 比較能用
